# Generated by Django 4.2.5 on 2023-10-06 14:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('date_published', models.DateField()),
                ('body_snippet', models.TextField()),
                ('full_content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
