# Generated by Django 4.2.5 on 2023-10-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_remove_blogpost_image_url_blogpost_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageIntroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
