# Generated by Django 4.2.5 on 2023-10-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_homepageintrocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageintrocontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepageintrocontent',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
