# Generated by Django 4.2.5 on 2023-10-10 15:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the tech blog post.', null=True, upload_to='techblog_images/')),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('body_snippet', models.TextField(default='Tech Blog')),
                ('full_content', ckeditor_uploader.fields.RichTextUploadingField(default='Tech Blog full content')),
                ('slug', models.SlugField(unique=True)),
                ('tech_type', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('test', 'Test'), ('other', 'Other')], help_text='Type of the technical blog post.', max_length=50)),
            ],
        ),
    ]
