# Generated by Django 4.2.5 on 2023-10-14 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_techblogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards/')),
                ('title', models.CharField(max_length=200)),
                ('short_intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='details/')),
                ('caption', models.CharField(max_length=300)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.card')),
            ],
        ),
    ]
