# Generated by Django 4.2.5 on 2023-10-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_card_imagedetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedetail',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='imagedetail',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
