# Generated by Django 4.2.5 on 2023-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_alter_card_options_card_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techblogpost',
            name='tech_type',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('ctdl&gt', 'CTDL & GT'), ('test', 'Test'), ('other', 'Other')], help_text='Type of the technical blog post.', max_length=50),
        ),
    ]
