# Generated by Django 4.2.5 on 2023-10-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_alter_techblogpost_tech_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techblogpost',
            name='tech_type',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('ctdl&gt', 'CTDL & GT'), ('test', 'Test'), ('other', 'Other'), ('raft', 'Raft')], help_text='Type of the technical blog post.', max_length=50),
        ),
    ]
